### PR TITLE
Fixes for various minor issues

### PR DESCRIPTION
**Pull request by normanthesquid**
Fixes for:
#82 
#83 
#84 
#85

### CODE REVIEW

**Comment by normanthesquid** [comment]
@Mad-Spy for the captain profile links - When should stuff be in the library vs the cat?

**Comment by Mad-Spy** [comment]
Thanks for this. Just a couple of things in case you want to do further work. Please go ahead and do this in future though!

- Don't forget to increment the file version numbers when you make a change.
- The entries in the Space Marine library deliberately don't have any rules which have Legion specific wording (i.e. <Chapter> gets replaced by BLOOD ANGELS, etc.) so they can be reused across all Legions. Anything with keyworded text should go as a link on the Root Selection entry in the visible catalogue.

**Comment by normanthesquid** [comment]
Cool, thanks for the feedback  - I wasnlt sure if the version numbers got auto-updated as part of releasing  the repo to appspot, or how that worked in general

**Comment by Mad-Spy** [comment]
> @Mad-Spy for the captain profile links - When should stuff be in the library vs the cat?

Libraries contain shared data. All Captains are the same datasheet, it's just the keywords that change on the model and its abilities. The Captain entry in the Library only has its shared keywords, not the Chapter specific ones. Those are added on the Root Selection Entry Link in the individual catalogues, along with the customised text for abilities which contain a \<CHAPTER\> keyword or replacement.

**Comment by normanthesquid** [comment]
Issue #63 seems related to that, but its Dark Angels specific. Should we take a look at all the various space marine factions to make sure they all have the correct abilities for those HQs?

**Pull request merged**
